config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products do
    resources :reviews
    resources :tags
  end

  # post '/users' => 'users#create'

  resources :users, :except => [:show, :new]


  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  get '/' => 'products#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/association.rb
class Association < ActiveRecord::Base
  belongs_to :product, foreign_key: :product_id
  belongs_to :tag, foreign_key: :tag_id
  # foreign_key specifies the foreign key name in the database.
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :associations
  has_many :tags, through: :associations

  has_attached_file :image,
                  styles: { thumb: ["100x100#", :jpg],
                            original: ['600x600>', :jpg] },
                  convert_options: { thumb: "-quality 75 -strip",
                                     original: "-quality 100 -strip" }

  validates :name, :presence => true
  validates :name, :length => {
    :minimum => 3,
    :maximum => 50,
    :too_short => "%{count} characters is the minimum allowed for a name.",
    :too_long => "%{count} characters is the maximum allowed for a name."
  }

  validates :price, :presence => true

  validates :category, :presence => true

  validates :description, :presence => true
  validates :description, :length => {
    :minimum => 20,
    :maximum => 250,
    :too_short => "%{count} characters is the minimum allowed for a product description.",
    :too_long => "%{count} characters is the maximum allowed for a product description."
  }

  validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }



end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :product, foreign_key: :product_id, optional: true
  # foreign_key specifies the foreign key name in the database.

  validates :author, :presence => true

  validates :rating, :presence => true
  validates :rating, :numericality => {
    :only_integer => true,
    :greater_than => 0,
    :less_than => 11,
    # Default error messages exist for these values.
  }

  validates :content, :presence => true
  validates :content, :length => {
    :minimum => 10,
    :maximum => 250,
    :too_short => "%{count} characters is the minimum allowed for this review",
    :too_long => "%{count} characters is the maximum allowed for this review"
  }

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :associations
  has_many :Products, through: :associations

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  validates :name, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end

  def authorize_admin
    if !current_user || current_user.admin == false
      flash[:alert] = "You aren't authorized to visit that page.  This requires an administrator account."
      redirect_to '/'
    end
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorize_admin, only: [:new, :create, :edit, :update, :destroy]

  def homepage
    render :home
    # This render will link to the specific html.erb document in the folder that matches the controller.
  end

  def index
    @products = Product.all
    @user = current_user
  end

  def show
    @product = Product.find(params[:id])
    @user = current_user
    @tag = Tag.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to  products_path
    else
      render :new
    end
  end

  def edit
   @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully edited!"
      redirect_to products_path
    else
      flash[:alert] = "Product edit failed!"
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully deleted!"
    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:name, :description, :price, :category, :image)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, only: [:new, :create]
  before_action :authorize_admin, only: [:edit, :update, :destroy]

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
    @product = @review.product
  end

  def update
    @review = Review.find(params[:id])
    @product = @review.product
    if @review.update(review_params)
      flash[:notice] = "Review successfully edited!"
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review successfully deleted!"
    redirect_to product_path(@review.product)
  end

private
  def review_params
    params.require(:review).permit(:author, :rating, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/products"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/products"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def create

    @product = Product.find(params[:product_id])
    @tag = @product.tags.new(tag_params)

    if @tag.save
      Association.create(product_id: @product.id, tag_id: @tag.id)
      flash[:notice] = "Tag successfully saved."
      redirect_to product_path(@product)
    else
      flash[:alert] = "There was a problem creating the tag. Please try again."
      redirect_to product_path(@product)
    end
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/products"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User successfully edited!"
      redirect_to users_path
    else
      flash[:alert] = "User edit failed!"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BonAppetizers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Philosopher" rel="stylesheet">
  </head>

  <body>


        <div id="sidebar">

          <div id="sidebardiv">
            <%= image_tag("cater.png", :alt => "rss feed") %><br><hr>
            <%= link_to "Home", "/" %><br><hr>
            <%= link_to "Services", "/products"%><br><hr>
            <%= link_to "Users", "/users"%><br><hr>
          </div>
          <%= flash[:alert] %>
          <%= flash[:notice] %>
        </div>


        <div id="header">

        </div>

        <div id="background">
          <h1 class="pushdown">Bon Appetizers</h1>
          <h1>Catering Services</h1>
        </div>

        <div id="content">

          <div id="minibackground">
          </div>

          <div id="output">
            <div id="outputyield">
            </div>
            </div>
          </div>

          <div id="parent">
            <div id="wide"><%= yield %></div>
            <div id="narrow"><div id="outputimage"></div>
          </div>


        </div>

        <div id="footer">
          <% if current_user %>
            <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
          <% else %>
            <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
          <% end %>
        </div>







  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>

  <%= f.submit  %>
<% end %>

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<%= render "form" %>

app/views/products/home.html.erb
<h2>Bon Appetizers Catering Services</h2>

<p> You have found your catering team for all occasions! Our website is designed to assist those who are planning any kind of event! Within, there is a wealth of information to help you plan your festive affair.
Our Event Design Team can assist you with every aspect of your event to ensure it is a smashing success.
We take care of all the details, from preparation to clean up. Our prices are disclosed up front in your event contract, and we do not impose hidden charges. Our team of highly qualified professionals will make any event a pleasure. From weddings to cocktail parties, or anything in between, Bon Appetizers is your best choice.
Our food reflects our commitment to exceptional quality. All meals are prepared under the guidance of one of our most renowned chefs and our menu items are prepared with a passion for perfection.

<%= link_to "A List of Availible Services", "products#home" %>
</p>
<!-- This is a breakthrough as it allows me to specify very specific page routes from the products_controller. -->
<!-- <%= link_to "Home", "/products/1" %> -->
<!-- This allows me to specify implicitly the url path -->

app/views/products/index.html.erb
<h2>Products</h2>

<ul>
  <% @products.each do |product| %>
    <%= image_tag(product.image.url(:thumb), class: 'media-object round') %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>



<hr>


<% if @user && @user.admin %>
  <%= link_to "New Product", new_product_path %>
<% end %>

<%= link_to "Home", "/" %>

app/views/products/new.html.erb
<h2>New Product</h2>

<%= render "form" %>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>


<%= image_tag(@product.image.url(:original), class: 'media-object') %>


<h4><%= @product.category %></h4>
<h3><%= @product.price %></h3>

<hr>
  <p><%= @product.description %></p>
<hr>


<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <ul>
    <% @product.reviews.each do |review| %>
      <li>
        <%= review.rating %> - <%= review.author %> |
        <%= review.content %>

        <% if @user && @user.admin %>
          <%= link_to "Edit", edit_product_review_path(@product, review) %> |
          <%= link_to "Delete", product_review_path(@product, review),
                                :data => {:confirm => "Are you sure?",
                                :method => "delete"} %>
        <% end %>

      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<hr>
<% if @user %>
  <p><%= link_to "Add a review", new_product_review_path(@product) %></p>
  <hr>
<% end %>


<p><%= link_to "Return to Products", products_path %></p>
<% if @user && @user.admin %>
  <p><%= link_to "Edit Product", edit_product_path(@product) %></p>
  <p><%= link_to "Delete Product", product_path(@product),
                        :data => {:confirm => "You sure?",
                        :method => "delete"} %></p>
<% end %>


<hr>


<% if @product.tags.any? %>
  <h4>Here are the tags for this product:</h4>

  <ul>
    <% @product.tags.each do |tag| %>
      <li>
        <h2><%= tag.name %></h2>
      </li>
    <% end %>
  </ul>
<% end %>

<div class="pushdown">
<%= form_for [@product, @tag] do |f| %>

  <div class="form-group">
    <%= f.label "Add a tag!" %>
    <%= f.text_field :name %>
  </div>

  <%= f.submit  %>
<% end %>
</div>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :rating %>
  <%= f.select :rating, [['1','1'],['2','2'],['3','3'],['4','4'],['5','5'],['6','6'],['7','7'],['8','8'],['9','9'],['10','10']] %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/edit.html.erb
<h2>Edit Review</h2>

<%= render "form" %>

app/views/reviews/new.html.erb
<h2>New review for <%= @product.name %></h2>

<%= render 'form' %>

app/views/users/edit.html.erb
<h2> Sign up</h2>
<%= form_for @user do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>

  <%= f.label "Administrator" %>
  <%= f.select :admin, [['Yes',true],['No',false]] %>

  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Edit User" %>
<% end %>

app/views/users/index.html.erb
<h2>List of all users currently logged in</h2>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, edit_user_path(user) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2> Sign up</h2>
<%= form_for @user do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>